# Generated by Django 4.0.6 on 2023-06-22 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='setReminder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
